/*
 * Java domain class for entity "SessionDetails" 
 * Created on 2021-08-13 ( Date ISO 2021-08-13 - Time 15:03:28 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
 
 /*
 * Created on 2021-08-13 ( 15:03:28 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.siddhartha.garments.repository;

import javax.transaction.Transactional;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.stereotype.Repository;

import com.siddhartha.garments.entity.SessionDetails;
import com.siddhartha.garments.entity.SessionDetailsId;

/**
 * <h2>SessionDetailsRepository</h2>
 *
 * createdAt : 2021-08-13 - Time 15:03:28
 * <p>
 * Description: "SessionDetails" Repository
 */
 
 
@Repository
public interface SessionDetailsRepository  extends JpaRepository<SessionDetails,SessionDetailsId> , JpaSpecificationExecutor<SessionDetails> {
	SessionDetails findByTempTokenid(String authToken);
	
	@Modifying
	@Transactional
	int deleteByTempTokenid(String tempTokenid);
}
