/*
 * Created on 2021-08-04 ( 19:48:34 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.siddhartha.garments.entity;

import java.io.Serializable;
import java.math.BigDecimal;

import lombok.Getter;
import lombok.Setter;

/**
 * Composite primary key for entity "LoginMaster" ( stored in table "LOGIN_MASTER" )
 *
 * @author Telosys
 *
 */

@Getter
@Setter
public class LoginMasterId implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY KEY ATTRIBUTES 
    private String     loginId ;
    
    private String     agencyCode ;
    
    private BigDecimal companyId ;
    
    private String     branchCode ;
    
     
}
