/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2021-08-13 ( Date ISO 2021-08-13 - Time 15:03:28 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2021-08-13 ( 15:03:28 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.siddhartha.garments.entity;


import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

import lombok.*;
import javax.persistence.*;
import java.io.Serializable;
import java.util.List;

import java.util.Date;
import javax.persistence.*;




/**
* Domain class for entity "SessionDetails"
*
* @author Telosys Tools Generator
*
*/
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@DynamicInsert
@DynamicUpdate
@Builder
@IdClass(SessionDetailsId.class)
@Table(name = "CLAIMS_MARINE_SESSION_TABLE")
public class SessionDetails implements Serializable {
 
private static final long serialVersionUID = 1L;
 
    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="LOGIN_ID", nullable=false, length=100)
    private String     loginId ;

    @Id
    @Column(name="TOKEN_ID", nullable=false, length=500)
    private String     tokenId ;

    //--- ENTITY DATA FIELDS 
    @Column(name="STATUS", length=50)
    private String    status ;

    @Column(name="TEMP_TOKENID", length=50)
    private String     tempTokenid ;

    @Column(name="ENTRY_DATE")
    private Date   entryDate; 
    
    @Column(name="SESSION_ID")
    private String   sessionId; ;


}



