/*
 * Created on 2021-08-13 ( 15:03:28 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.siddhartha.garments.entity;

import lombok.*;
import javax.persistence.*;
import java.io.Serializable;
import java.util.List;



/**
 * Composite primary key for entity "SessionDetails" ( stored in table "SESSION_DETAILS" )
 *
 * @author Telosys
 *
 */

@Setter
@Getter
@NoArgsConstructor
@EqualsAndHashCode
@AllArgsConstructor
public class SessionDetailsId implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY KEY ATTRIBUTES 
    private String     loginId ;
    
    private String     tokenId ;
    
     
}
